zuul:
  routes:
    users:
      path: /test/**
      #write here the route of the called Rest API, GET /greeting is the URL.
      url: http://example.com/greeting
      serviceId: myusers-service


logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace
myusers-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100 
